package com.fcfas.musikjaksel.model;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class IndieData {

    public static String[][] data = new String[][]{
            {"Barasuara", "Band", "Barasuara is a band from Indonesia, consisting of Iga Massardi (Vocals / Guitar), Gerald Situmorang (Bass), TJ Kusuma (Guitar), Asteriska (Vocal), Puti Chitara (Vocal) and Marco Steffiano (Drums). In 2015, they released their first studio album, Taifun , featuring the chart-topping singles Bahas Bahasa and Sendu Melagu. In 2016, Barasuara went on a tour called \"Taifun Tour\", which was a huge success in six big cities across Indonesia.\n" +
                    "\n" +
                    "It did not take long after the release of Taifun until Barasuara received numerous accolades appreciating the revolution that they made in the music industry. They won AMI Awards in 2016 for \"Best Alternative Production\" and received a nomination for \"Best New Artist\". In addition, the album \"Taifun\" was placed second in the “20 Best Indonesian Album 2015” list by Rolling Stone Indonesia, and was also listed in the “10 Best Indonesian Album of 2015” list by CNN Indonesia. Their constantly keen and sensational stage act has won them the \"Best Live Act\" award at Rolling Stone Indonesia Editorʼs Choice Award 2016. Furthermore, they were also nominated for “Breakthrough Artist of the Year” and “Best Album of the Year” from Indonesian Choice Awards 2016.\n" +
                    "\n" +
                    "Barasuara has only recently released their much-anticipated second studio album, ‘Pikiran dan Perjalanan’, under Indonesia's independent record label, Darlin' Records.", "https://www.wethefest.com/uploads/lineups/barasuara_jI4H7BwBhd.jpg", "https://www.youtube.com/user/barasuara"},
            {"Dipha Barus", "Producer / DJ", "Through years of his experience in Music Industry, starting from being a member on one of Indonesia’s most celebrated electronic group (Agrikulture), touring relentlessly to all cool clubs on major cities in Indonesia as a DJ, to become one of the most-sought producer that works with already well-known artist. Dipha Barus has established himself as a new musical phenomenon. His passion and dedication on always spreading good vibe through music by playing in front of thousands of electronic music festival attendees on headlining slot or through his studio outputs that’s been released on various record labels.\n" +
                    "\n" +
                    "Dipha Barus’ constantly making all his vision come through, his first single ‘No One Can Stop Us’ has been awarded ‘the best electronic music production of the year’ in AMI Awards 2016, and his latest single 'All Good' are one of the 50 viral Global Track on Spotify, a new record breaker for Indonesian / South East Asia artist.",
                    "https://www.wethefest.com/uploads/lineups/dipha-barus_W1326cKGIm.jpg", "https://www.youtube.com/user/diphabarustv"},
            {"Tulus", "Singer", "50 Awards both in the field of music and cinematography, have gained in the 7 years of his musical journey. Working with the way of independence, TULUS works under management of TulusCompany, the company he built with his brother, Riri Muktamar. TulusCompany as the record label and artist management has released 3 music albums for TULUS, called \"Tulus\", \"Gajah\", and \"Monokrom\". All music works in the three music albums are TULUS's own works.\n" +
                    "\n" +
                    "TULUS holds a bachelor's degree in architecture with endless love for music. Not only that, TULUS, collaborates with various professions outside the music industry. Among them, making music videos, video documentation, and art performances for music videos. Davy Linggar, Melati Suryodharmo, and Papermoon Puppet Theater are 3 of the many other names that have collaborated with TULUS. Not only in Indonesia, in 2015, TULUS also published his music works in Japan starting with the release of a Japanese song, \"Kutsu\". \"Kutsu\" is a composition of the song \"Sepatu\" in the Japanese version. After Japan, he also expanded to Malaysia. This began with the official launch of the \"Monokrom\" Album in Malaysia.",
                    "https://www.wethefest.com/uploads/lineups/tulus_l8A9xdsHF6.jpg", "https://www.youtube.com/user/musiktulus"},
            {".Feast", "Band", "Indonesian music group .Feast was formed in Jakarta at some point in 2012, revolving around the talents and audacity of Baskara Putra (also known as singer/songwriter Hindia), Ryo Bodat, Dicky Renanda, Adnan S.P. and F. Fikriawan when they were still students in Universitas Indonesia. The group has been catching regional media attention since their first single 'Camkan', and now heralded as one of the biggest next-generation band in Indonesia after the release of their genre-defying debut album 'MULTIVERSES' in September 2017. This reputation snowballed after the band published its nationally-acclaimed 'Beberapa Orang Memaafkan', which saw singles such as 'Peradaban' and 'Berita Kehilangan' (ft. Rayssa Dynta) claiming air time in FM radios across the archipelago and as far as Bangkok and Kuala Lumpur. .Feast is notorious for their reputation of amassing a crowd dangerous enough for stage security and utilizing collaborators and guest performers on-stage and in their recorded materials. Both of their albums include big names and new contenders alike in the Indonesian music scene, such as Mardial, Ramengvrl, Bam Mastro (of Elephant Kind), Karaeng Adjie (of Polka Wars), Oscar Lolang, Bin Idris, Sir Dandy and Rayssa Dynta.\n" +
                    "\n", "https://www.wethefest.com/uploads/lineups/feast_qavvoTBlXh.jpg", "https://www.youtube.com/channel/UC_WMZDQv29eJBMpv9PwWazw"},
            {"Dekat", "Trio", "Dekat, a vocal trio consisting of Mohammed Kamga, Tahir \"Tata\" Hadiwijoyo and Chevrina Anayang, writes their life stories and transforms them beautifully to songs that they made. They were formed in Jakarta, Indonesia, in the year of 2014.",
                    "https://www.wethefest.com/uploads/lineups/dekat_jCVntXokiY.jpg", "https://www.youtube.com/user/musikdekat"},
            {"Duara", "Duo", "Duara is a collective project by Robert MR and Renita Martadinata. Distancing themselves from their initial roots of Jazz and RnB, respectively, in this venture, the duo explore other sides of their musicality. Duara offers their version of pop music that is genreagnostic and easy listening, with the intent to provide the audience with an alternative flight of imagination.\n" +
                    "\n" +
                    "Their debut single, titled „And Time Froze“ was released in September 2018 and gained quite a critical acclaim from their fellow musicians. Their follow up single, “Sarariman’s Dream” is out on November 16.",
                    "https://www.wethefest.com/uploads/lineups/duara_JtQgkH3A7I.jpg", "https://www.youtube.com/channel/UCbDA4xT73RePcIgtUBCZevQ"},
            {"Elephant Kind", "Band", "Genre-bending trio, Elephant Kind, produce a modern classic in this decade displaying a mastery of mix genres. They debut in 2014 and quickly gained fan base who were sparked by Bam Mastro's distorted pop-warm, somnolent, slightly out of focus vocals and Bayu Adisapoetra’s reinvigorated slick beats and ferociously sensual bass lines from Kevin Septanto.\n" +
                    "\n" +
                    "The music project, however, was founded in 2013 by music producer and songwriter Bam Mastro during his studies at Western Australian Academy of Performing Arts (WAAPA). Born in Champaign, Illinois, U.S.A. and raised in so many different parts of the world such as China, Taiwan, Australia and Indonesia, Bam envisions to break down the barriers within culture through the music that he produced in Elephant Kind.\n" +
                    "\n" +
                    "Elephant Kind has released successful singles such as, True Love, Oh Well, With Grace, Montage and Beat The Ordinary. The band’s debut EP Scenarios: A Short Film by Elephant Kind was released November 2014. The band quickly received critical acclaim. Jakarta Beat named them Best New Artist of 2015 after the release of their second EP Promenades: A Short Film by Elephant Kind in 2015. The two time AMI nominee was also nominated as best new artist by Indonesia’s Choice Award and also Anugerah Musik Indonesia in 2017.",
                    "https://www.wethefest.com/uploads/lineups/elephant-kind_E3PpM6e4jF.jpg", "https://www.youtube.com/user/ElephantKind"},
            {"Endah n Rhesa", "Duo", "Endah N Rhesa  is a music project comprising acoustic guitar, bass and vocal. The musical nuance that Endah N Rhesa tries to bring out is Folk, Jazz, Blues, Rock and Roll, and Ballads. Endah Widiastuti (vocal, guitar) and Rhesa Aditya (Bass) met each other in a rock band in early 2003. Shortly after the two left the band in 2004, Endah went solo, just like the way it used to be before joining the rock band. Endah recorded numerous song of hers in an album entitled ”THE NEW BEGINNING”, a four-track mini album which was independently distributed, with a limited number of copies. in one of the songs in the album, Rhesa added some bass thumps and made it a fascinating mix of the three instruments (vocal, guitar and bass). The song is titled “WHEN YOU LOVE SOMEONE”. From that time being, Endah and Rhesa started to play together in campus events, and the feedback toward their music were tremendously positive. Finally, they decide to create a stage name for their duo/musical project which comes from their own names: Endah N Rhesa\n" +
                    "\n" +
                    "Endah N Rhesa was inspired to start playing in minimalist acoustic format, Surprisingly, because of some local bands, namely: Cozy Street Corner and Bonita and Anda. In terms of singing, Endah is influenced by Alanis Morissete and Norah Jones. Besides, there are also the four John’s that influence her in playing guitar: John Mayer, John Butler, John Scofield and John Frusciante. Endah also credits Pat Matheny and the multi-talented instrumentalist Warman Nasution  for her source of inspiration. Rhesa, on the other hand, is a unique personality who is mainly influenced guitarist like Jack Johnson, Dave Matthews, Jaes Taylor and other folk and ballad musicians. The Persons that Rhesa put into credit for making him play bass are Les Claypool, Victor Wooten, Flea and ex-child singer Bondan Prakoso. They both, however, share the same influence in music, to wit: Bela Fleck & The Flecktones, Which Affects them mostly on creating rich groovy and harmonic nuances in the music of Endah N Rhesa.",
                    "https://www.wethefest.com/uploads/lineups/endah-n-rhesa_FxrEooBJld.jpg", "https://www.youtube.com/user/endahnrhesa"},
            {"Eva Celia", "Singer", "Celia is a jazz singer-songwriter, guitarist, and lyricist. As the daughter of a well-known musician, she says that she was influenced by the music she heard at home growing up, even though she was never pressured by her father to pursue music. She released her first singles, \"Reason\" and \"Against Time,\" in 2015. She followed up the next year with her first album, And So It Begins. Performers on the album included Indra Lesmana, Aldhan Prasatya, Demas Narawangsa, and Tendra, and members of Snarky Puppy. In 2016, she was nominated for Penyanyi Solo Pria/Wanita Soul/R&B/Urban Terbaik in the Indonesian Music Awards.\n" +
                    "In 2017, she received nominations for both Album of the Year and Female Singer of the Year at the Indonesian Choice Awards.\n" +
                    "Her early public performances included Java Jazz 2013, where she performed with her father, Indra Lesmana. In 2017, she performed as part of \"3 Stories, 1 Room,\" a tour of six Indonesian cities with musicians Kunto Aji and Jordi Waelauruw.",
                    "https://www.wethefest.com/uploads/lineups/eva-celia_WTiBJJ8zKX.jpg", "https://www.youtube.com/channel/UC14i2C_trePnN_hJgxPVxCw"},
            {"Fourtwnty", "Duo", "Fourtwnty is a iconic duo indie band", "https://www.wethefest.com/uploads/lineups/fourtwnty_oiSnxCLJOR.jpg", "https://www.youtube.com/user/fourtwntymusic"},
            {"Fun On A Weekend feat. Soul Menace", "Group", "Fun On a Weekend (FOAW) is an electronic trio formed by Evan Virgan, Kenny Gabriel, and Winky Wiryawan. Signed under Inspire Artistry, FOAW brings out the fresh sound of House, Tribal, Jazz House, Acid, Breaks, Disco House, and Future House. Each member has distinctive characteristics when performed, all blending into one. This makes their set exciting and powerful for partygoers to enjoy. \n" +
                    "\n" +
                    "Winky Wiryawan is no stranger to Indonesia’s electronic dance music scene. He’s been in the industry for the past twenty years and still counting. Always doung his best to keep up with the trend without leaving his own trademark House and Breaks sounds. \n" +
                    "\n" +
                    "Evan Virgan was only 16 when he first produced his own music back in his hometown, Bali. He got signed as one of the official Asian artist from Spain, Pacha Recording. So far he has shared the deck with famous names like Paul Thomas, Sied van Riel, Starkillers, Sander van Doorn,Steve Aoki, Laidback Luke, DVBBS,Norman Jay, etc. He play at biggest dance music festival in Indonesia its “Djakarta Warehouse Project” 2014, play alongside with ; Martin Garrix,Steve Aoki,Nicky romero,Laidback Luke,and more. \n" +
                    "\n" +
                    "Kenny Gabriel is a newcomer and winner of NET TV’s very own The Remix Season 2. He’s one the roster act Internationally acclaimed Jazz festival, JAVA JAZZ in 2015, 2016, and 2017.",
                    "https://www.wethefest.com/uploads/lineups/fun-on-a-weekend-ft_11RrpkXkXd.jpg", "https://soulmenace.com/"},
            {"Gerald Situmorang feat. Sri Hanuraga", "Duo", "Gerald Situmorang was born in Jakarta on May 31, 1989. He began playing guitar at the age of 13. Initially, he studied under Armstrong Pitoi of the New Breeze for 3 years, Nikita Dompas for one year where he improved his skills and grew his passion in jazz, and later he took private lessons at Institut Musik Daya with Dion Janapria for one semester. He has also participated at \"Serambi Jazz Workshop\" with Florian Ross, Henning Sieverts, Wolfgang Haffner, and Kai Brückner. He also took a Masterclass with Indra Lesmana.\n" +
                    "\n" +
                    "Gerald Situmorang has performed with many musicians, including : Tohpati, Erwin Gutawa, Indra Lesmana, Riza Arshad, Aksan Sjuman, Barry Likumahuwa, Raisa, Monita Tahalea, Agnez Mo, Efek Rumah Kaca, Matajiwa, Indra Aziz, Nikita Dompas, Mery Kasiman, Ayushita, Calvin Jeremy, Oran Etkin and many more.\n" +
                    "\n" +
                    "----\n" +
                    "\n" +
                    "Sri “Aga” Hanuraga moved to Amsterdam from Jakarta, Indonesia to broaden his musical horizons. Since his father is a classical guitar player, Aga naturally showed more interest to the guitar during his early childhood and took lessons from his father. At the age of 13, Aga saw a video by the progressive Rock Band “ELP” which caused his interest in the piano to grow, and he decided to start studying piano under the guidance of his father. Since then, he has played in progressive rock and fusion bands and performed at several big festivals and at the AMI Sharp Awards 2002. \n" +
                    "\n" +
                    "\n" +
                    "At the age of seventeen, Aga began to study Jazz piano with Indra Lesmana, the leading Jazz pianist in Indonesia. During that period he won the ﬁrst prize at the JGTC Competition, and performed at some major Jazz festivals in Indonesia including the International Java Jazz Festival 2005. \n" +
                    "\n" +
                    "\n" +
                    "Aged nineteen, he moved to Amsterdam to study Jazz piano at the Conservatory of Amsterdam. In April 2006 he won the soloist prize at the East of Eastern Jazz Festival in Nijmegen. In January 2009 he won the second prize in the YPF Jazz Piano Competition, a Dutch national piano competition, with jury such as Jacky Terrason, John Taylor, Antonio Farao, Enrico Pieranunzi and Bobo Stenson) \n" +
                    "In February 2010 his trio “Animated” was chosen to play at the Dutch Jazz Day in May 2010 and his composition was chosen to be released on a CD called “The Best Of Jazz Day”. \n" +
                    "\n" +
                    "\n" +
                    "In 2011, he was awarded with the “The Indonesian Young Talent Award” by the Java Jazz Festival. Soon after that, he won The European Keep an Eye Jazz Award 2011 for the category “Best Band” with the Daniel Master Quartet. In June 2011 he graduated summa cum laude (10 with distinction) from the master program in Jazz piano performance at The Conservatorium van Amsterdam. \n" +
                    "In 2012 Sri awarded the 3rd prize at the Hoeilaart Jazz Competition with the Philip Czarnecki Quintet. With the NY Quartet Sri has performed in Korea at the 2012 Jarasum showcase program (Jara-sum Int.Jazz Festival, EBS TV station, LIG Hall). His composition ,Spyros The Dragon was nominated for ICEMA best jazz composition.\n" +
                    "\n" +
                    "\n" +
                    "During his stay in The Netherlands, he has been performing in many important stage such as North Sea Jazz Festival 2011, Concertgebouw and Bimhuis. He also toured extensively with different projects to Paris, Nice, Cannes, Monaco, Belgium, Hungary, Germany,Israel, Poland ,South Korea, North Korea  and Romania.\n" +
                    "\n" +
                    "\n" +
                    "He also took a part as a sideman on saxophonist Giulia Barba's debut album, “The Angry St.Bernard” . This album was chosen as album of the year of 2013 by the dutch jazz magazine Jazzism. \n" +
                    "\n" +
                    "\n" +
                    "His latest album, “To The Universe” was chosen as album of the year by JGTC Festival 2015, Beehype and Tempo Magazine.\n" +
                    "In September 2016 he was awarded the Indonesian grammy (AMI Awards) for the best jazz instrumental artist.\n" +
                    "Recently he has the honour of replacing the late Riza Arshad in a legendary Indonesian band called Simak Dialog.\n" +
                    "\n" +
                    "\n" +
                    "He has performed with many notable International artists and Indonesian musicians, among others Alex Sipiagin, Mokhtar Samba, Tohpati, Dewa Budjana, Riza Arshad, Dira Sugandi, Gerald Situmorang and Monita Tahalea. Aside from performing, He was commisioned by Goenawan Mohamad to write music for his poem, “Don Quixote” \n" +
                    "\n" +
                    "\n" +
                    "in 2018 he performed with the great Harvey Mason at The Java Jazz Festival 2018.",
                    "https://www.wethefest.com/uploads/lineups/gerald-situmorang-sri-hanuraga_GMjzb2je1I.jpg", "https://www.youtube.com/user/geraldsitumorang"},
            {"Glaskaca", "Band", "After a month Glaskaca released the single 'Atom', this alternative rock group from Jakarta re-released its new material titled 'Banda' as of Friday August 31, 2018. The song was chosen as the third single to introduce the first full album 'Addendum' which will be released in the near future . While presenting visuals in slow motion, Glaskaca presents 'Banda' in the video lyrics concept. This number can also be enjoyed through digital platforms such as Spotify, Apple Music, and Joox.\n" +
                    "\n" +
                    "Through this song, Glaskaca again proved that his music space was unlimited. 'This song sounds different from the other songs on the 'Addendum' album later because we really don't give limits to music, so we are free to explore as much as possible,' said Rayhan Noor, guitarist and composer of the lyrics.\n" +
                    "\n" +
                    "Also included in the album 'Addendum', this single release voiced the moment of human self-reflection. 'The Banda Islands describe the phase of reflection itself. Silence, stay away from the vortex for a while,' Rayhan explained again. 'At the same time, the island also gave a message not to be afraid and keep fighting. Like the islands in Banda, even though they are small and surrounded by sea, they can be ferocious at times, but still survive and remain beautiful.' ",
                    "https://www.wethefest.com/uploads/lineups/glaskaca_DQCo7CqME4.jpg", "https://www.youtube.com/channel/UClf4rtc92IQv0ENcJoUusgg"},
            {"Grrrl Gang", "Band", "Everyone has been forming their band with people they go to school with since time immemorial, and Angeeta Sentana, Edo Alventa and Akbar Rumandung are no exceptions. The trio are based in Yogyakarta, where their school is located. Grrrl Gang is an indie pop/rock project that brings to mind the likes of Talulah Gosh, Veronica Falls, Alvvays, etc. Their double-single \"Bathroom/Thrills\" have drawn a lot of attention, cementing them as crowd favorites before the band even releases a full-length album.",
                    "https://www.wethefest.com/uploads/lineups/grrrl-gang_7QZV1oEs2g.jpg", "https://www.youtube.com/channel/UC2bMfCXtzwBmTmi0u4M84tg"},
            {"Kelelawar Malam", "Band", "Kelelawar Malam are an Indonesian punk rock group uniting various influences from horror films, literatures and other dark imageries to create their own remarkable sound.\n" +
                    "\n" +
                    "In the early years, Sayiba and Deta formed the group aiming to become a tribute band of an american horror punk rock group, The Misfits, before finally deciding to write and record their own materials in 2008. In the same year, their first ep was released—featuring top songs ‘Jalan Gelap’ and ‘Bangkit Dari Kubur’.\n" +
                    "\n" +
                    "As Indonesian kids who grew up in the 90s, Sayiba and Deta drew inspirations mainly from the legendary Indonesian horror character Suzanna. As the vocalist and lyricist of the group, Sayiba writes all of the songs, from campy horror stories, literatures, to Indonesian B-horror movies, while Deta takes part as the visual artist, ranging from woodcut, ink and watercolor techniques as seen on Kelelawar Malam’s artworks.\n" +
                    "\n" +
                    "In 2010, they released their first studio album called ‘Kelelawar Malam’. The self-titled album was crowned the 6th position in Rolling Stone Indonesia's 20 Best Indonesian Albums in 2010. \n" +
                    "Seven years later, after the arrival of new members and the release of vinyl records for their self-titled album, they released the second studio album called ‘Jalan Gelap’. Their renowned approach to punk rock music apparent in the album was again crowned the 3rd position in Rolling Stone Indonesia's 20 Best Indonesian Albums in 2017. In the same year and the following year, they were invited to perform in South Korea and Japan.",
                    "https://www.wethefest.com/uploads/lineups/kelelawar-malam_TLYlxiMTRu.jpg", "https://www.youtube.com/watch?v=YlmtjG58lAg"},
            {"Kunto Aji", "Singer", "Kunto Aji is an Indonesian Male Singer and Songwriter who rosed to fame after winning the Indonesian Idol season. His debut singles from his debut album entitled “Generation Y” are “Terlalu Lama Sendiri”, “Ekspektasi”, “Akhir Bulan”, and “Mercusuar”.\n" +
                    "\n" +
                    "With those songs from “Generation Y” album, Kunto Aji won Breakthrough Artist of The Year in Indonesian Choice Awards in 2015. In the year of 2017, he currently is preparing his second album, to be released in the year of 2018. In November 2017, Kunto Aji released his newest single, \"Konon Katanya\".",
                    "https://www.wethefest.com/uploads/lineups/kunto-aji_O6ZcpfyLmU.jpg","https://www.youtube.com/user/KubisLaut"},
            {"Matter Halo", "Duo", "AMI Awards-nominated visionary pop duo from Jakarta— Matter Halo — has recently returned with a new single for “Million” via Interlokal.\n" +
                    "\n" +
                    "After four years taken flight with their conceptual debut album Aerotiva, the band (Ibnu Dian and Ganidra Rai) turn up with a dreamy, funky, and low-key groove. Produced by Matter Halo, Mixed by Bam Mastro (Elephant Kind) and Mastered by Greg Calbi (David Bowie, Arcade Fire, Cigarettes After Sex), “Million” hits from their original synth textures, and smooth-bouncing rhythm and bass line towards a 90's Jonny Greenwood-inspired guitar solo surprise, and the easy-loving, melodious refrain.\n" +
                    "\n" +
                    "\"We want to bring a pop song that people can listen to either from their vinyl player or streaming services and a vibe that people dreamily slow dance to in their living room.\" Ibnu explained. Listen to “Million\" here.\n" +
                    "\n" +
                    "Matter Halo which have released three EPs and one documentary, emerged in 2015 with the release of the Brian Eno's Music for Airport-highly inspired debut album, Aerotiva and quickly went on number one in the Indonesian iTunes Chart on the same day of the release. Their wondrous singles which listened since 2008 have brought the band to be featured in huge international festival in Indonesia such as from Java Rockin’ Land in 2010 to the main stage of We The Fest in 2016. One of the tracks 'Teralih (feat. Nadin) [Aero’s Tape]' is featured as a soundtrack for an Indonesian film Posesif (2017) and listed in 5 Best Folk/Country/Ballad Production Work nominees by Ami Awards 2018.",
                    "https://www.wethefest.com/uploads/lineups/matter-halo_PxP3MVYKnj.jpg", "https://www.youtube.com/user/matterhalo"},
            {"Nadin Amizah", "Singer", "Nadin Amizah, or commonly referred as her Instagram nickname @cakecaine, is an Indonesian young singer, songwriter and influencer. She was first noticed by the public for her collaboration with the prominent Indonesian DJ Dipha Barus called ‘All Good’ in 2017. Before starting her career, she debuted in one of Indonesia’s TV station programs “Social Media Sensation” managed by TransTV in 2016, and came out as the third winner. Nadin Amizah has received various accolades, including the Indonesian Music Award 2017 in the Best Dance or Electronic Production Work. Nadin Amizah, through Sorai, released her first single \"Rumpang\" on September 14, 2018 on All Audio Digital Platform following up the great enthusiasm of her followers and fans. \"Rumpang\" live taking music video version on June 21, 2018 has been uploaded via the YouTube channel and has reached 1 Million views within 2 months. Now, Nadin release her second single ‘Sorai’ on January 1, 2019 to all audio digital platform to start the new year of 2019. The song is about being thankful for the memories made in 2018.",
                    "https://www.wethefest.com/uploads/lineups/nadin-amizah_VJaYJSMLm9.jpg", "https://www.youtube.com/channel/UCrorPql9QrqeSBNFNckfEcw"},
            {"Pamungkas", "Singer", "Pamungkas is a singer-songwriter as well a music producer from Jakarta, Indonesia. His first introduction to music was at the age of eight through the drums. Self-taught himself to play piano and guitar after that- before getting himself into singing and songwriting. His music heavily influenced by many British Music such as The Beach Boys, Radiohead, The Beatles, The Smiths, Arctic Monkeys. His songwriting style is inspired by the likes of the fab duo Lennon/McCartney, John Mayer, the norwegian Sondre Lerche and of course Bob Dylan. His musical library also shaped by the modern-electronic artists such as Disclosure, FKJ, Maggie Rogers, Jacob Collier, Rex Orange County, Ruby Empress.\n" +
                    "\n" +
                    "Pamungkas forming his own style of music by merging the essence of Folk, the richness of Electronic sounds and the catchiness of Pop. On top of that, his bright-powerful-soothing voice completed the whole thing and creates this new fresh dimension of sounds. His storytelling skills really is just the icing on the cake. Having that in hand, he single handedly present his debut LP, \"Walk The Talk\" in June 2018. He write, sing, produce, mix, master and design it himself. As a 25 years old adult-teen, he shared his thoughts and perspectives about life, love, friendship and self-growth through his lyrics.",
                    "https://www.wethefest.com/uploads/lineups/pamungkas_yFA2C3HRnX.jpg", "https://www.youtube.com/user/rpamungkas"},
            {"Petra Sihombing", "Singer", "Big in families close to music, Petra grew to be a figure who was not only good at singing, but also good at playing guitar and piano. Not to mention the support obtained from the handsome face and big name of the father, complete capital for success in the world of entertainment.\n" +
                    "\n" +
                    "Petra's musical talent has been seen since he was 3 years old. However, after growing up, this 182 cm tall boy began to be ashamed to sing, as a boy. Quitting singing, Petra started playing drums at the age of 7 and guitar at the age of 12. A year later, he began making songs and arranging. All Petra's musicality honed itself with his father.\n" +
                    "\n" +
                    "Support from the family made him decide to make an album with his own songs and arrangements. The songs were taken by Petra from a collection of songs he created since 15 years.\n" +
                    "\n" +
                    "Unfortunately, no major label company would accept it. Therefore, he decided to distribute his album indie. Therefore, the father also had to sell a car to finance this first album.\n" +
                    "\n" +
                    "From Indie's sales, Petra was 'applied' by a label and appeared on several music programs on television. The name, song, and appearance of Petra began to be liked by Indonesian music lovers, and his song Cinta Tak Wherever became popular. At present Petra is still studying Music Composition at the Indonesian Music Institute (IMI).",
                    "https://www.wethefest.com/uploads/lineups/petra-sihombing-ft-enrico-octaviano_2FR3BHsLsE.jpg", "https://www.youtube.com/user/petrasihombingmusic"},
            {"Puti Chitara", "Singer", "A singer-songwriter, born in Kelantan, Malaysia and since early childhood was raised and surrounded by a musical family. Her mother was a well-known musician from the early 70’s in Indonesia and her father is a music enthusiast whom introduced her with variety of music and instruments. At 5 years old, she started to learn to play classical piano and taking courses at the Royal School of Music, Malaysia and passed each grade with distinction until grade 6, where she moved to Indonesia. She also learns how to play the guitar, taught by her mother and also took violin classes.  \n" +
                    "\n" +
                    "Then Puti Chitara continued her bachelor degree at Ritsumeikan Asia Pacific University, Japan receiving scholarships from the Japanese government and SANYO for 4 years’ study. During her study in Japan, she involved in many musical activities such as APU Orchestra, Pianokko, performing in multicultural festivals and finally starts writing her own songs in Japanese. She participated in a number of auditions held by record labels in Japan and eventually reached the final for Sony Japan Tobilabo Audition.\n" +
                    "\n" +
                    "In 2009, she graduated from university with a title Bachelor of Social Science where she successfully took course in comparative musicology, and her final dissertation about Javanese gamelan entitled ‘Resonance of Javanese Sound in Japan and Indonesia’ received a prestigious university award as an ‘Outstanding Thesis of Fall Semester 2009’.  \n" +
                    "\n" +
                    "Returning to Indonesia, Puti Chitara starts her music career as an Independent musician by submitting demos and uploading through Soundcloud that took her to many chances in performing at number of local gigs and finally released her debut album ‘Sarsaparilla Dream’ on 2014 under the label, Demajors and she was selected to perform in Singapore. In that year also, she joined a band Barasuara as one of the vocalist and currently active with the tours and music producing. In 2017, Puti Chitara released her second solo album ‘Goodnight’. Early 2018, she released her very first song in Bahasa Indonesia, ‘Gelembung Kaca’ featuring the phenomena Efek Rumah Kaca frontman, Cholil Mahmud. Then another single by the end of 2018, ‘Ruang Baja’. On February 2019, Puti Chitara released a soundtrack for an Indonesian horror movie ‘Sunyi’ with the same title, adapted from a Korean horror movie ‘Whispering Corridors’ (1998).\n" +
                    "\n" +
                    "Puti Chitara’s music are mainly influenced by classical music which she was earlier introduced and cites her most favorite composers such as Tchaikovsky, Claude Debussy, Saint-Saens and Japanese composer, Hisaishi Joe, which makes most of her music involved many tunes of orchestral instruments and compositions. She also listens to number of notable musicians; Carpenters, Bread, Utada Hikaru, Kanno Yoko, Lana Del Rey and many others.  Her music is known as gloomy ballad, dark yet decorated with simple lyrics, which are relatable and sometimes could be fun and soothing. Most of her songs are written in English but currently starting to release number of songs in Bahasa Indonesia and inspired by her daily life and personal events. Currently Puti Chitara is working on her third album, which is scheduled to be released on 2019.",
                    "https://www.wethefest.com/uploads/lineups/puti-chitara_OsHh9jzwOC.jpg", "https://www.youtube.com/user/putichitara"},
            {"Sal Priadi", "Singer", "Even though he's a new guy in the block, Sal Priadi has given a new breath in Indonesian pop music scene with his magical romantic songs with a touch of Pop Ballad. With just only two songs in his belt, Sal Priadi has made himself to be nominated as Best Male Pop Singer in the highest musical award in Indonesia, Anugrah Musik Indonesia 2018.\n" +
                    "\n" +
                    "With the help of his written poetries, rusty guitar, his fellow musician, and simple bedroom recording tools, Sal Priadi started to record his first view songs. Only after he took courage to finally uploaded on SoundCloud, people started to ask for more. An intimate presence that was shared, straight from the comfort of his bedroom.\n" +
                    "\n" +
                    "Year after, Sal Priadi has released his four singles (“Kultusan”, “ikat Aku Di Tulang Belikatmu”, “Melebur Semesta”, and “Jangan Bertengkar Lagi Ya? OK? OK!”). Now available on Spotify.\n" +
                    "\n" +
                    "Murky yet flamboyant, with the touch of strings, piano, and accoustic guitar to accompany love and tragedy in his lyrics, Sal Priadi pesents a new wave of peculiar emotions ro give a new color to Indonesia’s music industry.",
                    "https://www.wethefest.com/uploads/lineups/sal-priadi_ZKrOiGjDE4.jpg", "https://www.youtube.com/user/salpriadi"},
            {"Sore", "Band", "Jakarta-based indie band formed in 2002. The band was originally formed by Ade Paloh, Mondo Gascaro and Awan Garnida. They have been close friends since childhood. Other two members, Bemby Gusti and Reza Dwiputranto, were brought in by Awan Garnida.\n" +
                    "\n" +
                    "In 2004 and early 2005, Sore contributed two songs in a couple of compilation albums, the first one wasin a compilation album of Jakarta’s indie scene called \"JKRT: SKRG\" (an abbreviation of \"Jakarta, Sekarang\" which translates to \"Jakarta, Now\"). The album was released by Aksara Records. Another one was an original motion picture soundtrack of \"Janji Joni\". The album was also released by Aksara Records.\n" +
                    "\n" +
                    "SORE finally released their full-length debut album Centralismo in 2005. The album title itself refer to the world \"central\", which in this case refer to Central Jakarta, where the most band members grew up. The music varied greatly from track to track as each member contributed lead singing and song-writing in this album. Their vintage instrumentation, like the use of vibraphones, mellotron, and horn section is reminiscent of popular music in the 50's, 60's and 70's.\n" +
                    "\n" +
                    "The first album was praised by Time Magazine Asia as \"One of Five Asian Albums Worth Buying\", and Rolling Stone Indonesia magazine ranked it the 40th in \"150 Greatest Indonesian Albums of All Time\". The fifth single, \"No Fruits for Today\", also ranked as one of 150 Greatest Indonesian Albums of All Time.",
                    "https://www.wethefest.com/uploads/lineups/sore_DNuSV0Hhpm.jpg", "https://www.youtube.com/watch?v=ujrgek6_tpM"},
            {"The Adams", "Band", "The Adams was formed in Jakarta, Indonesia in 2002 on the grounds of the Jakarta Institute of Arts, a fertile environment for kids looking to start a band. Their blend of crunching guitars, sweet harmonies, memorable melodies and relatable lyrics promptly placed them among the leading lights of the city's emerging independent music scene, releasing albums The Adams and v2.05 to commercial and critical acclaim in 2005 and 2006 respectively, while building up a nationwide following through a rigorous touring schedule.\n" +
                    "\n" +
                    "While in the ensuing years the band members have been busy with their personal lives and other endeavors, it is a testament to the enduring strength of songs such as \"Konservatif\", \"Waiting\", \"Halo Beni\" and \"Hanya Kau\" that they remained an in-demand live act that performed at various major Indonesian music festivals and served as the opening act for renowned British band Bloc Party in Jakarta during their 2013 Asia tour.\n" +
                    "\n" +
                    "In 2017 the band made its entire back catalogue available on digital music services, including the ß Release EP which collected previously-released non-album tracks and an all-new version of \"Glorious Time\". The same year also saw the band make a triumphant debut appearance at We The Fest.\n" +
                    "\n" +
                    "In 2019, The Adams finally released their long-awaited third album, Agterplaas, with songs such as \"Pelantur\", \"Masa-Masa\" and \"Timur\" quickly becoming firm fan favorites. Agterplaas sees the band retaining its signature sound while pushing the limits of their musical abilities, with lyrics that remain relatable while reflecting their maturity as adults.\n" +
                    "\n" +
                    "The Adams consists of Ario Hendarwan (vocals, guitar), Saleh Husein (vocals, guitar), Gigih Suryo Prayogo (vocals, drums) and Pandu Fathoni (vocals, bass).",
                    "https://www.wethefest.com/uploads/lineups/the-adams_8M5UqgHzry.jpg", "https://www.youtube.com/user/theadamsofficial"},
            {"Polka Wars", "Band","For millennial Indonesian hipsters, Polka Wars is a wet dream come true. Four members in their mid-20s who are cool, Polka Wars plays melodic rock music full of aura and indie aesthetics, referring to global post-punk sounds, modern folk, afro-pop, and electro. Their charming debut album, Axis Mundi, offers 8 songs that at a glance remind you of many big names in the realm of British-American indie music such as Interpol, Fleet Foxes, Yeasayer and Wildbeasts.\n" +
                    "\n" +
                    "But it is far from just imitating artists who influence the sound of Polka Wars - whoever they are - the quartet consists of Karaeng Adjie (vocals, guitar), Billy Aulia Saleh (guitar), Xandega Tahajuansya (bass), and drummer Giovanni Rahmadeva successfully summarizing the familiar sounds their own work.\n" +
                    "\n" +
                    "All of the songs in Axis Mundi were right on target, whether it was Karaeng's semi-baritone vocal voice, the beautiful games of two guitars that complemented each other, or Rahmadeva's percussion action that aroused emotions. All instruments feel complementary without having to stand out on their own. Like a good album, Axis Mundi managed to capture the atmosphere of four friends who were playing music together. Even though their live action - complete with additional electric piano and brass section - is sometimes too dependent on excessive elements of Baroque music, the Axis Mundi album always feels minimalist and intimate even in the most abrasive parts. The opening songs \"Mokele\" and \"Moths & Flies\" with smooth bass and phrasing guitars create epic dynamics through the play between musicians rather than stale tricks. Crescendo feels natural, and the verse and chorus don't feel like formula. Subtle melodic vocal curves make each part feel new (Now! This is the chorus!).",
                    "https://awsimages.detik.net.id/visual/2018/04/17/d5435a7d-c03c-4a5f-b46f-8809629e68fd_169.jpeg?w=650", "https://www.youtube.com/channel/UC4W_NhU6BN-K5lzaU8AN_Rw"},
            {"The Panturas", "Band", "The Panturas is a surf rock band hailed from the land with no proximity near the beach, Jatinangor. Consisting of Abyan (Vocal & Guitar), Rizal (Guitar), Bagus Patria (bass) and Surya (drum). The Panturas bring summer ocean tunes inspired by The Ventures, Dick Dale and Eka Sapta.\n" +
                    "\n" +
                    "Formed in early 2016, The Panturas introduced themselves by releasing a single called ‘Fisherman’s Slut’. Their first single successfully caught everyone’s attention.\n" +
                    "\n" +
                    "More than 10.000 have watched the lyric video to ‘Fisherman’s Slut’ on Youtube which brought them to be on of the performers at We The Fest 2017, sharing a stage with a well-known musician from around the world. Not only have they performed at the big music festival, but The Panturas was also one of the headliners at one of the notable micro gigs in Jakarta, Thursday Noise volume 10. And recently they have successfully held 2 sold out showcases in Bandung & Jakarta.",
                    "https://www.wethefest.com/uploads/lineups/the-panturas_vGT85BKwTx.jpg", "https://www.youtube.com/channel/UC3bAHHGb6_IFJifehkM1T7g"}
    };

    public static ArrayList<Indie> getListData() {
        Indie indie =  null;
        ArrayList<Indie> list = new ArrayList<>();
        for (String[] aData : data) {
            indie = new Indie();
            indie.setName(aData[0]);
            indie.setCategory(aData[1]);
            indie.setRemarks(aData[2]);
            indie.setPhoto(aData[3]);
            indie.setLinkcontent(aData[4]);

            list.add(indie);
        }

        return list;
    }
}
